# Generated by Django 6.0.3 on 2026-05-25 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pago_email_motivo_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloBloqueoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('url_patron', models.CharField(help_text='Prefijo de URL a bloquear, ej: /menu/', max_length=200)),
                ('motivo', models.TextField(blank=True, default='', max_length=500)),
                ('bloqueado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'modulos_bloqueo',
            },
        ),
        migrations.RemoveField(
            model_name='pedidomodel',
            name='codigo_pedido',
        ),
        migrations.CreateModel(
            name='CarritoItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField(default=1)),
                ('subtotal', models.FloatField()),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='users.productomodel')),
            ],
            options={
                'db_table': 'carrito_items',
            },
        ),
        migrations.CreateModel(
            name='DetallePagoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pago', models.ForeignKey(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='users.pagomodel')),
            ],
            options={
                'db_table': 'detalle_pagos',
            },
        ),
    ]
