# Generated by Django 6.0.3 on 2026-05-25 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_modulo_bloqueo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioTurnoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_actual', models.CharField(max_length=20)),
                ('hora_inicio_actual', models.CharField(max_length=5)),
                ('hora_fin_actual', models.CharField(max_length=5)),
                ('dia_solicitado', models.CharField(max_length=20)),
                ('hora_inicio_solicitada', models.CharField(max_length=5)),
                ('hora_fin_solicitada', models.CharField(max_length=5)),
                ('motivo', models.TextField(max_length=500)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True, default='', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_turno', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(blank=True, db_column='horario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='users.horariomodel')),
            ],
            options={
                'db_table': 'solicitudes_cambio_turno',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
