from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView

from users.forms import EmailPasswordResetForm, StyledSetPasswordForm
from users.infrastructure.views.admin_list_views import (
    categoria_create_view,
    categoria_delete_view,
    categoria_edit_view,
    categorias_list_view,
    empleados_list_view,
    clientes_fieles_view,
    modulos_bloqueo_view,
    horario_create_view,
    horario_delete_view,
    horario_edit_view,
    horarios_list_view,
    solicitudes_turno_list_view,
    solicitud_turno_responder_view,
    inventario_create_view,
    inventario_list_view,
    mesa_create_view,
    mesa_edit_view,
    mesas_list_view,
    enviar_correo_masivo_view,
    noticia_admin_create_view,
    pagos_list_view,
    pago_create_view,
    pedidos_list_view,
    pedido_create_view,
    pedido_edit_view,
    producto_create_view,
    producto_edit_view,
    productos_list_view,
    promocion_create_view,
    promocion_delete_view,
    promocion_edit_view,
    promociones_list_view,
    reserva_create_view,
    reservas_list_view,
    user_create_view,
    user_delete_view,
    user_edit_view,
    user_toggle_bloqueo_view,
    users_list_view,
)
from users.infrastructure.views.auth_views import (
    PasswordResetEmailView,
    login_view,
    logout_view,
    register_view,
)
from users.infrastructure.views.panel_views import (
    admin_dashboard_view,
    cancelar_reserva_cliente_view,
    home_redirect_view,
    mi_horario_view,
    mi_perfil_view,
    pedidos_asignados_view,
    reserva_detalle_mesero_view,
    reservas_hoy_mesero_view,
    reservas_sse_view,
    solicitud_turno_crear_view,
    mis_solicitudes_turno_view,
    mis_notificaciones_view,
    marcar_notificaciones_leidas_view,
)
from users.infrastructure.views.insumo_views import (
    insumos_list_view,
    insumo_create_view,
    insumo_edit_view,
    receta_view,
    reporte_reposicion_view,
    insumo_carga_masiva_view,
)
from users.infrastructure.views.reportes_views import reportes_admin_view, reportes_pdf_view
from users.infrastructure.views.public_views import (
    api_mesas_disponibilidad,
    carrito_agregar_view,
    carrito_checkout_view,
    carrito_quitar_view,
    carrito_vaciar_view,
    carrito_view,
    index_view,
    menu_view,
    noticias_view,
    pedido_confirmado_publico_view,
    pedido_procesar_pago_view,
    reserva_confirmada_view,
    reserva_crear_view,
    reserva_view,
)

urlpatterns = [
    path('', home_redirect_view, name='index'),
    # Alias: rutas típicas de Django / tutoriales que si no existen devuelven 404
    path(
        'recuperar-contrasena',
        RedirectView.as_view(url='/recuperar-contrasena/', permanent=False),
    ),
    path(
        'password_reset/',
        RedirectView.as_view(url='/recuperar-contrasena/', permanent=False),
    ),
    path(
        'password_reset',
        RedirectView.as_view(url='/recuperar-contrasena/', permanent=False),
    ),
    path(
        'password-reset/',
        RedirectView.as_view(url='/recuperar-contrasena/', permanent=False),
    ),
    path(
        'password-reset',
        RedirectView.as_view(url='/recuperar-contrasena/', permanent=False),
    ),
    path(
        'accounts/password_reset/',
        RedirectView.as_view(url='/recuperar-contrasena/', permanent=False),
    ),
    path(
        'accounts/password_reset',
        RedirectView.as_view(url='/recuperar-contrasena/', permanent=False),
    ),
    path(
        'login/recuperar/',
        RedirectView.as_view(url='/recuperar-contrasena/', permanent=False),
    ),
    path('dashboard/', admin_dashboard_view, name='admin_dashboard'),
    path('users/nuevo/', user_create_view, name='admin_user_create'),
    path('users/<int:pk>/edit/', user_edit_view, name='admin_user_edit'),
    path('users/<int:pk>/delete/', user_delete_view, name='admin_user_delete'),
    path('users/<int:pk>/bloqueo/', user_toggle_bloqueo_view, name='admin_user_bloqueo'),
    path('users/', users_list_view, name='admin_users'),
    path('empleados/', empleados_list_view, name='admin_empleados'),
    path('clientes-fieles/', clientes_fieles_view, name='admin_clientes_fieles'),
    path('modulos-bloqueo/', modulos_bloqueo_view, name='admin_modulos_bloqueo'),
    path('categorias/nuevo/', categoria_create_view, name='admin_categoria_nuevo'),
    path('categorias/<int:pk>/edit/', categoria_edit_view, name='admin_categoria_edit'),
    path('categorias/<int:pk>/eliminar/', categoria_delete_view, name='admin_categoria_eliminar'),
    path('categorias/', categorias_list_view, name='admin_categorias'),
    path('productos/nuevo/', producto_create_view, name='admin_producto_nuevo'),
    path('productos/<int:pk>/editar/', producto_edit_view, name='admin_producto_edit'),
    path('productos/', productos_list_view, name='admin_productos'),
    path('promociones/nuevo/', promocion_create_view, name='admin_promocion_nuevo'),
    path('promociones/<int:pk>/editar/', promocion_edit_view, name='admin_promocion_edit'),
    path('promociones/<int:pk>/eliminar/', promocion_delete_view, name='admin_promocion_eliminar'),
    path('promociones/', promociones_list_view, name='admin_promociones'),
    path('inventario/nuevo/', inventario_create_view, name='admin_inventario_nuevo'),
    path('inventario/', inventario_list_view, name='admin_inventario'),
    path('insumos/nuevo/', insumo_create_view, name='admin_insumo_nuevo'),
    path('insumos/<int:pk>/editar/', insumo_edit_view, name='admin_insumo_edit'),
    path('insumos/carga-masiva/', insumo_carga_masiva_view, name='admin_insumo_carga_masiva'),
    path('insumos/', insumos_list_view, name='admin_insumos'),
    path('productos/<int:producto_pk>/receta/', receta_view, name='admin_receta'),
    path('reposicion/', reporte_reposicion_view, name='admin_reposicion'),
    path('mesas/nuevo/', mesa_create_view, name='admin_mesa_nuevo'),
    path('mesas/<int:pk>/edit/', mesa_edit_view, name='admin_mesa_edit'),
    path('mesas/', mesas_list_view, name='admin_mesas'),
    path('reservas/nuevo/', reserva_create_view, name='admin_reserva_nuevo'),
    path('reservas/', reservas_list_view, name='admin_reservas'),
    path('pedidos/nuevo/', pedido_create_view, name='admin_pedido_nuevo'),
    path('pedidos/<int:pk>/editar/', pedido_edit_view, name='admin_pedido_edit'),
    path('pedidos/', pedidos_list_view, name='admin_pedidos'),
    path('pagos/nuevo/', pago_create_view, name='admin_pago_nuevo'),
    path('pagos/', pagos_list_view, name='admin_pagos'),
    path('horarios/nuevo/', horario_create_view, name='admin_horario_nuevo'),
    path('horarios/<int:pk>/editar/', horario_edit_view, name='admin_horario_edit'),
    path('horarios/<int:pk>/eliminar/', horario_delete_view, name='admin_horario_delete'),
    path('horarios/', horarios_list_view, name='admin_horarios'),
    path('solicitudes-turno/', solicitudes_turno_list_view, name='admin_solicitudes_turno'),
    path('solicitudes-turno/<int:pk>/responder/', solicitud_turno_responder_view, name='admin_solicitud_turno_responder'),
    path('mi-solicitud-turno/', solicitud_turno_crear_view, name='solicitud_turno_crear'),
    path('mis-solicitudes-turno/', mis_solicitudes_turno_view, name='mis_solicitudes_turno'),
    path('mis-notificaciones/', mis_notificaciones_view, name='mis_notificaciones'),
    path('mis-notificaciones/leer/', marcar_notificaciones_leidas_view, name='notificaciones_leer'),
    path('reportes/pdf/', reportes_pdf_view, name='reportes_pdf'),
    path('reportes/', reportes_admin_view, name='reportes_admin'),
    path('carrito/agregar/', carrito_agregar_view, name='carrito_agregar'),
    path('carrito/quitar/', carrito_quitar_view, name='carrito_quitar'),
    path('carrito/vaciar/', carrito_vaciar_view, name='carrito_vaciar'),
    path('carrito/finalizar/', carrito_checkout_view, name='carrito_finalizar'),
    path('pedido/pago/', pedido_procesar_pago_view, name='pedido_procesar_pago'),
    path('pedido/confirmado/<int:pk>/', pedido_confirmado_publico_view, name='pedido_confirmado_publico'),
    path('carrito/', carrito_view, name='carrito'),
    path('menu/', menu_view, name='menu'),
    path('correo-masivo/', enviar_correo_masivo_view, name='admin_correo_masivo'),
    path('noticias/admin/nuevo/', noticia_admin_create_view, name='admin_noticia_nuevo'),
    path('noticias/', noticias_view, name='noticias'),
    path('public/noticias/', noticias_view, name='noticias_public'),
    path('reserva/', reserva_view, name='reserva'),
    path('reserva/crear/', reserva_crear_view, name='reserva_crear'),
    path('reserva/confirmada/', reserva_confirmada_view, name='reserva_confirmada'),
    path('api/mesas/disponibilidad/', api_mesas_disponibilidad, name='api_mesas_disponibilidad'),
    path('login/', login_view, name='login'),
    path(
        'recuperar-contrasena/',
        PasswordResetEmailView.as_view(
            template_name='auth/password_reset_form.html',
            form_class=EmailPasswordResetForm,
            email_template_name='auth/password_reset_email_txt.html',
            html_email_template_name='auth/password_reset_email.html',
            subject_template_name='auth/password_reset_subject.txt',
            success_url=reverse_lazy('password_reset_done'),
        ),
        name='password_reset',
    ),
    path(
        'recuperar-contrasena/enviado/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='auth/password_reset_done.html',
        ),
        name='password_reset_done',
    ),
    path(
        'restablecer-contrasena/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='auth/password_reset_confirm.html',
            form_class=StyledSetPasswordForm,
            success_url=reverse_lazy('password_reset_complete'),
        ),
        name='password_reset_confirm',
    ),
    path(
        'restablecer-contrasena/listo/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='auth/password_reset_complete.html',
        ),
        name='password_reset_complete',
    ),
    path('registro/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('mi-perfil/', mi_perfil_view, name='mi_perfil'),
    path('reserva/<int:pk>/cancelar/', cancelar_reserva_cliente_view, name='cancelar_reserva_cliente'),
    path('mi-horario/', mi_horario_view, name='mi_horario'),
    path('pedidos-asignados/', pedidos_asignados_view, name='pedidos_asignados'),
    path('reservas-hoy/', reservas_hoy_mesero_view, name='reservas_hoy_mesero'),
    path('reservas-hoy/<int:pk>/', reserva_detalle_mesero_view, name='reserva_detalle_mesero'),
    path('reservas-sse/', reservas_sse_view, name='reservas_sse'),
]
